language: node_js
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    addons:
      apt:
        packages:
          - rpm
          - g++-multilib
          - libxss-dev:i386
          - snapd
  - os: osx
    osx_image: xcode8.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi

install:
  - yarn

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export CSC_IDENTITY_AUTO_DISCOVERY=false; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release --x64 --mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release --x64 --linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release --ia32 --linux deb rpm; fi

branches:
  only:
    - master
    - develop
    - hotfix

notifications:
  email:
    on_success: never
    on_failure: change
